YaST package search
SUSE/connect pull request #434
Opened 2020-01-22 09:37 UTC by imobachgs

This PR extends the YaST API to access to the package search functionality. It is needed in order to implement the [online search feature](https://jira.suse.com/browse/SLE-9109).

2020-04-07 08:51 UTC, lagartoflojo commented
Hey @imobachgs, we just noticed this PR. Is it needed for 15 SP2?

2020-04-21 08:50 UTC, imobachgs commented
@lagartoflojo It would be a nice improvement, but it can wait until SP3. After all, the *online feature* is already finished and I guess we do not introduce new changes unless it is strictly needed. Thanks a lot!

2020-04-21 09:15 UTC, lagartoflojo commented
I've added it to our backlog so we review it once we get a chance. We're super busy with the Day 2 migration right now :(

2020-08-24 14:44 UTC, ngetahun commented
@imobachgs Can you please resolve the merge conflict?

2020-08-25 08:20 UTC, ngetahun commented
![](https://github.trello.services/images/mini-trello-icon.png) [[CNT] [REVIEW] YaST package search](https://trello.com/c/JX0PXKNl/1585-cnt-review-yast-package-search)

2020-08-26 09:03 UTC, ngetahun requested changes

2020-08-26 09:03 UTC, ngetahun commented on package/SUSEConnect.changes
> +Wed Jan 22 09:05:17 UTC 2020 - Imobach Gonzalez Sosa <igonzalezsosa@suse.com>
Update the date.

2020-08-26 12:39 UTC, ngetahun approved these changes
LGTM!

2020-08-26 13:05 UTC, imobachgs commented
> LGTM!

Thanks a lot!

2020-08-26 15:07 UTC, merged