Ruby ver replace in spec
SUSE/connect pull request #450
Opened 2020-11-23 08:21 UTC by Zennoe

As it turns out, SUSEConnect exists twice: in /usr/sbin and in the ruby gem folder. 
In addition to that I forgot to bump the gem version in my PR.

2020-11-23 11:17 UTC, suse-tests-pass commented
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/364443/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged db3f4f2c769f90ef268cce49818fe0c05b68b9b2 into 324403bba2056322db9dc4ab2730ba67453698aa)

2020-11-23 11:34 UTC, digitaltom commented
@Zennoe could you prepend to your latest line in `.changes`: `Update to 0.3.29:`?

2020-11-23 11:37 UTC, digitaltom requested changes
@Zennoe could you prepend to your latest line in .changes: Update to 0.3.29:?

2020-11-24 07:40 UTC, suse-tests-pass commented
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/364685/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 2c9b58d9d8a159aa3776bde34a873ff68f6e6ce1 into 324403bba2056322db9dc4ab2730ba67453698aa)

2020-11-24 08:43 UTC, digitaltom approved these changes

2020-11-24 11:06 UTC, merged